steps:
  # Paso 1: Construir la imagen Docker (Usamos todo en minúsculas y sin guiones para ser consistentes)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA', '.']

  # Paso 2: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deploy-whatsapp-cloudbuild'
      - '--image'
      - 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - '--allow-unauthenticated'

# Opciones de Logging para evitar el error de Service Account
options:
  logging: CLOUD_LOGGING_ONLY

# Reemplazá 'tu-cuenta@tu-proyecto' con los datos reales de tu Service Account
#serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/tu-cuenta@$PROJECT_ID.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA'
