steps:
  # Paso 1: Construir la imagen Docker (Usamos todo en minúsculas y sin guiones para ser consistentes)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA', '.']

  # 2. SUBIR la imagen al registro (ESTO ES LO QUE FALTA)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deploy-whatsapp-cloudbuild'
      - '--image'
      - 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--no-allow-unauthenticated'
      - '--vpc-connector'
      - 'whatsapp-bot-vpc-connecto' # <--- REEMPLAZA con el nombre de tu conector VPC Serverless Access
      - '--set-secrets'
      - 'PYWA_VERIFY_TOKEN=PYWA_VERIFY_TOKEN:latest,\
         PYWA_AUTH_TOKEN=PYWA_AUTH_TOKEN:latest,\
         PYWA_PHONE_ID=PYWA_PHONE_ID:latest,\
         DB_USER=DB_USER:latest,\
         DB_PASSWORD=DB_PASSWORD:latest,\
         DB_NAME=DB_NAME:latest,\
         DB_HOST=DB_HOST:latest,\
         DB_PORT=DB_PORT:latest'

# Opciones de Logging para evitar el error de Service Account
options:
  logging: CLOUD_LOGGING_ONLY

# Reemplazá 'tu-cuenta@tu-proyecto' con los datos reales de tu Service Account
#serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/tu-cuenta@$PROJECT_ID.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/laslocaswhatsapp:$COMMIT_SHA'
