services:
  app:
    build: .
    container_name: daniebot_app
    ports:
      - "5000:8080"
    volumes:
    # Montamos la carpeta de configuración de gcloud dentro del contenedor
      - C:\Users\danie\AppData\Roaming\gcloud:/root/.config/gcloud:ro
    environment:
      - GOOGLE_CLOUD_PROJECT=784310446531
    restart: always
    env_file:
      - .env
  ngrok:
    image: ngrok/ngrok:latest
    container_name: daniebot_ngrok
    depends_on:
      - app
    command: http app:8080
    ports:
      - "4040:4040"   # interfaz web de ngrok para ver las requests
    env_file:
      - .env
