import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from database.models.Products import Base, Products
from database.models.ProductImages import ProductImages 


import sys
import os

# Print sys.path to debug module search paths
#print("sys.path:", sys.path)

# Add the project root directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
#print("Updated sys.path:", sys.path)

# Load environment variables
load_dotenv()

# Database connection parameters
DB_USER = os.getenv("DB_USER", "bot_laslocas")
DB_PASSWORD = os.getenv("DB_PASSWORD", "Neverl0l")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_DATABASE", "laslocas_db")
DB_HOST_DOCKER = os.getenv("DB_HOST_DOCKER")  # For Docker connectivity

# Create the database URL
DATABASE_URL = f"postgresql+pg8000://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

def initialize_database():
    print(f"DEBUG: Conectando con usuario: {DB_USER} a la base {DB_NAME}")
    try:
        # Create the database engine
        print(f"DEBUG: Conectando con usuario: {DB_USER} a la base {DB_NAME} ")
        print("Create_engine init_db.py")
        engine = create_engine(DATABASE_URL, echo=True, pool_pre_ping=True)

        # Create all tables based on the models
        Base.metadata.create_all(engine)
        print("Database and tables created successfully.")

        # Insert initial data (optional)
        with Session(engine) as session:
            initial_product = Products(
#                product_id=None,  # Auto-generated by SERIAL
                description="denim jean",
                price=999,
                status=True,
            #    gallery_photos=None,
                cod_product="D123",
                item_title="Denim Jeans",
                name="Denim",
                extract_date=None  # Default to current timestamp
            )
            session.add(initial_product)
            session.commit()
            print("Initial data inserted successfully.")

    except Exception as e:
        print(f"Error initializing database: {e}")

if __name__ == "__main__":
    initialize_database()